GRANT USAGE ON * . * TO 'root'@'localhost' IDENTIFIED BY 'ehsan' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

GRANT ALL PRIVILEGES ON `4.3.4world` . * TO 'root'@'localhost' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `4.3.4char` . * TO  'root'@'localhost' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `4.3.4au` . * TO  'root'@'localhost' WITH GRANT OPTION;
